---
- hosts: all
  gather_facts: false
  tasks:
  - name: Update Apt
    become: true
    apt:
      update_cache: true
      cache_valid_time: 1500

  - name: Install basics
    become: true
    apt: name={{item}} state=latest
    with_items:
    - git
    - ansible
    - firefox
    - stow
    - entr # Cross-platform file-watcher
    - build-essential
    - clang-4.0
    - variety # wallpaper manager
    - p7zip-full

  - name: Symlink clang++-4.0 to clang++
    become: true
    file:
      src: /usr/bin/clang++-4.0
      dest: /usr/bin/clang++
      state: link
  - name: Symlink clang-4.0 to clang
    become: true
    file:
      src: /usr/bin/clang-4.0
      dest: /usr/bin/clang
      state: link

    # need to create a config directory so stow doesn't create item
    # as a symlink
  - name: Create config directory
    file: path=~/.config/ state=directory

  # Commenting this out because I'm making local modifications to it
  # - name: Git configs
  #   git: repo=https://github.com/bbkane/backup.git dest=~/backup

  - name: Stow common
    command: stow common
    args:
      chdir: ~/backup
      creates: ~/.gitconfig

  - name: Git nvim config
    git: repo=https://github.com/bbkane/nvim.git dest=~/.config/nvim

  # # As of 2017-07-29, this Neovim installation by Ansible fails
  # # Still works manually, though it complains
  # # apt_repository: repo='ppa:neovim-ppa/stable'
  # # stable is only for 16.04 :(
  # - name: Install Neovim Ansible apt workarounds
  #   become: true
  #   apt: name={{item}} state=latest
  #   with_items:
  #   # Need this so adding Neovim's repo works
  #   - software-properties-common
  #   # This is needes to apt can update the cache on Nvim install
  #   # https://github.com/ansible/ansible/issues/18987
  #   - aptitude
  # - name: Add Neovim Repo
  #   become: true
  # apt_repository: repo='ppa:neovim-ppa/unstable' state=absent
  # - name: Install Neovim
  # become: true
  # apt: name={{item}} update_cache=true
  # with_items:
  # - python3-dev
  # - python3-pip
  # - neovim

  - name: Install Neovim pip module
    become: true
    pip: name=neovim executable=pip3

  - name: Create Neovim config directory
    file: path=~/.config/nvim/autoload state=directory

  - name: Install plug.vim
    get_url: >
      url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest=~/.config/nvim/autoload/plug.vim

  - name: Update Editor
    become: true
    alternatives: name=editor path=/usr/bin/nvim link=/usr/bin/editor

  - name: Check if VS-Code is installed
    command: which code
    register: vscode_installed
    ignore_errors: true
  - name: Install Visual Studio Code
    become: true
    when: vscode_installed|failed
    apt:
      # https://code.visualstudio.com/download
      deb: https://go.microsoft.com/fwlink/?LinkID=760868
  - name: Symlink VSCode Settings
    command: python install_vs_code_settings.py --batch
    args:
      chdir: ~/backup/vscode/
      creates: ~/.config/Code/User/settings.json
  - name: Install NodeJS for VSCode
    become: true
    apt: name={{item}} state=latest
    with_items:
    # TODO: maybe install this with a PPA or nvm
    - nodejs
    - npm

  # TODO: make symlink from nodjs to node so TypeScript can find it
  - name: Symlink nodejs to node
    become: true
    file:
      src: /usr/bin/nodejs
      dest: /usr/bin/node
      state: link

  - name: Install TypeScript
    become: true
    npm:
      name: typescript
      global: yes

  - name: Install RVM Dependencies
    become: true
    apt:
      name: software-properties-common
      state: latest
  - name: Add PPA
    become: true
    apt_repository:
      repo: 'ppa:rael-gc/rvm'
      update_cache: false # Neovim PPA means this won't work... I'll do it manually for now
  - name: Add RVM
    become: true
    apt:
      name: rvm
  - name: Add bkane to RVM group
    become: true
    user:
      name: bkane
      groups: rvm
      append: true
  # Note: Need to restart to make sure I'm part of the group
  #
  # Note: after Ansible 2.3, use path instead of dest
  # Note: if there is no unique mark, block will overwrite each other
  - name: Source common.sh in .bashrc
    blockinfile:
      dest: ~/.bashrc
      block: |
        # Source common config
        source ~/.config/common.sh
        # TODO: put this in machine.sh
        # Source rvm to use ruby
        source /usr/share/rvm/scripts/rvm
  - name: Install dropbox
    shell: curl -L "https://www.dropbox.com/download?plat=lnx.x86_64" | tar -C $HOME -xzf -
    args:
      creates: ~/.dropbox-dist/dropboxd
    # For now, I'm just always going to manually start it...
    # TODO: add systemd start and enable here

  # TODO: add Anaconda install

  # https://rg3.github.io/youtube-dl/download.html
  - name: Install youtube-dl
    become: true # I'm installing to /usr/local/bin
    get_url:
      url: https://yt-dl.org/downloads/latest/youtube-dl
      dest: /usr/local/bin/youtube-dl
      mode: a+rx
      # NOTE: this is for the 2017-08-13 version
      checksum: sha256:94419dbb390bddcb7582312398ea6fa3bce9ea8d9cc5f0092fab85e79d900579
