# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
  {
    hostname: 'host',
    ip: '192.168.33.10'
  },
  {
    hostname: 'client',
    ip: '192.168.33.11'
  }
]

# NOTE: as this is currently written, it will run each time Vagrant is invoked...
# write Ansible host
File.open('hosts.ini', 'w') do |fp|
  fp.puts('# Generated by Vagrant')
  boxes.each do |box|
    fp.puts(box[:hostname])
  end
end

# build what to append in /etc/hosts
etc_host_append = "# Generated by Vagrant\n"
boxes.each do |box|
  etc_host_append << "#{box[:ip]} #{box[:hostname]}\n"
end

Vagrant.configure('2') do |config|
  # set settings common to all VMs
  config.vm.box = 'centos/7'
  # Disable the default synced folder because it's too much trouble to set up
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder '.', '/home/vagrant/sync', disabled: true

  # Don't check the host key
  config.ssh.verify_host_key = false

  # Add some VirtualBox specific settings
  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  # modify /etc/hosts so boxes can ping each other
  config.vm.provision "shell" do |s|
    s.name = 'Modify /etc/hosts'
    s.inline = 'printf "$1" >> /etc/hosts'
    s.args = [etc_host_append]
  end

  # Create and set VM specific settings
  boxes.each do |box|
    config.vm.define box[:hostname] do |node|
      node.vm.hostname = box[:hostname]
      node.vm.network 'private_network', ip: box[:ip]
    end
  end
end
